root: true
extends:
  - '@remix-run/eslint-config'
  - '@remix-run/eslint-config/node'
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - eslint:recommended
  - '@willin'
  - prettier
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
plugins:
  - import
rules:
  camelcase: 0
  react/react-in-jsx-scope: 0
  react/jsx-no-target-blank: 0
  jsx-a11y/no-noninteractive-tabindex: 0
  '@typescript-eslint/explicit-function-return-type': 0
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: ./
settings:
  import/resolver:
    typescript: {}
